package net.middlemind.GenAsm.Linkers;

import net.middlemind.GenAsm.Assemblers.Assembler;

/**
 * An interface that defines the basic linker class.
 * @author Victor G. Brusca, Middlemind Games 07/30/2021 10:18 AM EST
 */
public interface Linker {
    /**
     * The main execution method used to link areas generated by an assembler.
     * @param assembler             An instance of an assembler that can assemble the target source file.
     * @param assemblySourceFile    The file path of the assembled source.
     * @param outputDir             The target directory for output files.
     * @param otherObj              An optional generic object that can be used to customize the linker if applicable.
     * @param verbose               A Boolean value indicating that verbose logging should be used.
     * @param quellOutput           A Boolean value indicating that file output should be disabled.
     * @throws Exception 
     */
    public void RunLinker(Assembler assembler, String assemblySourceFile, String outputDir, Object otherObj, boolean verbose, boolean quellOutput) throws Exception;    
}
